.PHONY: clean All

All:
	@echo "----------Building project:[ GAPGO - Debug ]----------"
	@cd "GAPGO" && "$(MAKE)" -f  "GAPGO.mk"
clean:
	@echo "----------Cleaning project:[ GAPGO - Debug ]----------"
	@cd "GAPGO" && "$(MAKE)" -f  "GAPGO.mk" clean
